### PR TITLE
feat: basics

### LINKED ISSUE #3: Feature: basic infrastructure
**Goal of this feature**

Get the bot running like it's supposed to

### PR DESCRIPTION
**Pull request by Chicken**
Closes #3 

**Task list**

- [x] basic commands
  - [x] stop
  - [x] eval
  - [x] ping
- [x] database (rss feed & settings)
- [x] permission handling
- [x] interaction handling
- [x] slash command handler

### CODE REVIEW

**Review by eemunni — APPROVED** [review]
LGTM

**Review by eemunni — APPROVED** [review]
Looks good to me 👍

**Comment by Jipes** [comment]
Im monke

**Review by weebi — APPROVED** [review]
Yep, works like a dream

**Pull request merged**
